Этап 2
m00rl00n/java-explore-with-me pull request #16
Opened 2023-09-05 08:27 UTC by m00rl00n

2023-09-07 05:13 UTC, EugeneLenkevich requested changes
Привет, Виктория! Спасибо за PR.

Все замечательно, все по делу. Предлагаю немножко улучить логирование, добавить в лог побольше идентификаторов, так будет потом проще разбираться в случае каких то проблем. Обычно, при разбирательстве, ищут по логу как раз идентификаторам так как параллельно может идти множество запросов и надо как то их различать чтобы понять что именно упало и с какими входными данными (но тут надо аккуратно, не всегда допустимо чтобы в лог попадала вся информация, ПДн например или счета карт те же) :)

2023-09-07 05:13 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +@AllArgsConstructor
Лучше все таки @RequiredArgsConstructor

Если добавиться, например, стоковое поле со значением настройки в классе, то ломбок ее тоже будет пытаться засунуть в конструктор :)

2023-09-07 05:13 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public CategoryDto add(NewCategoryRequestDto newCategoryRequestDto) {
А давай ка еще над все методы сервисов, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними :)

2023-09-07 05:13 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        log.info("Изменение категории....");
Можно даже вот так залогировать, чтобы потом, по логу, в случае диагностики ошибок на проде том же было понятно что в метод пришло

 log.info("Изменение категории, categoryId = {}", categoryId);
 log.debug("categoryDto = {}",  categoryDto);

2023-09-08 12:15 UTC, EugeneLenkevich requested changes
Давай все таки конкатенацию строк из логирования уберем, а то все таки дипломная работа, некошерно :)

2023-09-08 12:15 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        log.info("Удаление категории...id=" + categoryId);
` log.info("Удаление категории...id = {}", categoryId);`

Вот так, с плейсхолдером.
К тому же, конкатенация сток вызывается всегда, а вот если мы используем плейсхолдер, то конкатенация происходит только в том случае, когда у нас установлен соответствующий уровень логирования. То есть мы так расходуем кучу памяти просто на ровном месте если у нас если у нас, например, куча логов log.trace log.debug при уровне логирования INFO :)

2023-09-09 15:43 UTC, EugeneLenkevich approved these changes
Во, шикарно, спасибо :)

2023-09-11 06:50 UTC, m00rl00n commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        log.info("Удаление категории...id=" + categoryId);
Спасибо за ревью! Приступаю к 3 части  :)

2023-09-11 10:42 UTC, merged